blog/config/routes.rb
Blog::Application.routes.draw do

  resources :posts
  
  root 'welcome#index'

end

blog/app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true,
	length: { minimum: 5 }
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Marvania</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

blog/app/views/posts/edit.html.erb
<h1>Editing Event</h1>
 
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', posts_path %>

blog/app/views/posts/index.html.erb
<h1>Listing Events</h1>
<%= link_to "Marvania", controller: "posts" %>

<%= link_to 'New event', new_post_path %>
<table>
	<tr>
		<th>Title</th>
		<th>Text</th>
		<th></th>
		<th></th>
	</tr>

	<% @posts.each do |post| %>
		<tr>
			<td><%= post.title %></td>
			<td><%= post.text %></td>
			<td><%= link_to 'Show', post %></td>
			<td><%= link_to 'Edit', edit_post_path(post) %></td>
		</tr>
	<% end %>
</table>

blog/app/views/posts/new.html.erb
<h1>New Event</h1>
<%= form_for :post, url: posts_path do |f| %>
  
  <% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', posts_path %>

blog/app/views/posts/show.html.erb
<p>
	<strong>Title:</strong>
	<%= @post.title %>
</p>
 
<p>
	<strong>Text:</strong>
	<%= @post.text %>
</p>

<%= link_to 'Back', posts_path %>
| <%= link_to 'Edit', edit_post_path(@post) %>

blog/app/views/welcome/index.html.erb
<h1>Welcome to Marvania!</h1>

<%= link_to "Events", controller: "posts" %>

<%= link_to 'New event', new_post_path %>